**Added:** None

**Changed:** None

**Deprecated:** None

**Removed:** None

**Fixed:**

* Fixed a bug where the bash completer raised an exception when using Python 3.6.

**Security:** None

